// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADaI_PPvN84ykzN8vQD2mjKU1tPmmkFJI',
    appId: '1:814762444234:web:8946f862320e69f9297b33',
    messagingSenderId: '814762444234',
    projectId: 'chatx-8b91a',
    authDomain: 'chatx-8b91a.firebaseapp.com',
    storageBucket: 'chatx-8b91a.firebasestorage.app',
    measurementId: 'G-KRW0BH7SR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXY5aQ7F04lMGuOQa2OvOOHljd89tSH4',
    appId: '1:814762444234:android:a354e3455e2170ba297b33',
    messagingSenderId: '814762444234',
    projectId: 'chatx-8b91a',
    storageBucket: 'chatx-8b91a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0M7_4LtWpYCuBUo8uBvXKc7rJrNcR2ng',
    appId: '1:814762444234:ios:dbc87472c288dbf3297b33',
    messagingSenderId: '814762444234',
    projectId: 'chatx-8b91a',
    storageBucket: 'chatx-8b91a.firebasestorage.app',
    iosBundleId: 'com.app.chatx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0M7_4LtWpYCuBUo8uBvXKc7rJrNcR2ng',
    appId: '1:814762444234:ios:dbc87472c288dbf3297b33',
    messagingSenderId: '814762444234',
    projectId: 'chatx-8b91a',
    storageBucket: 'chatx-8b91a.firebasestorage.app',
    iosBundleId: 'com.app.chatx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADaI_PPvN84ykzN8vQD2mjKU1tPmmkFJI',
    appId: '1:814762444234:web:ad7cfffc024533eb297b33',
    messagingSenderId: '814762444234',
    projectId: 'chatx-8b91a',
    authDomain: 'chatx-8b91a.firebaseapp.com',
    storageBucket: 'chatx-8b91a.firebasestorage.app',
    measurementId: 'G-8XV16JTGDR',
  );
}
